name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: 'Run by cypress command line'
        default: 'cypress/e2e/*'

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    
    container:
      image: cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1
      options: --user 1001
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install  
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }} 
          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  